### ISSUE TITLE
vCenter $Object.Name does not exist

### ISSUE THREAD

**Issue by jpsider** [WahlNetwork/Vester#116]
This does not prevent tests from running, its simply a reporting bug.

It could be resolved by replacing '$cfg.vcenter.vc' with '$global:DefaultVIServer' in 'VesterTemplate.Tests.ps1' where the '$InventoryList' is created.

Would this cause problems for the future if you allow multiple vcenter connections?

**Comment by jpsider** [comment]
Console output Before:
Describing vCenter Configuration: NFC-UseSSL.Vester.ps1
Describing vCenter Configuration: SMTP-Port.Vester.ps1
 [+] vCenter  - SMTP Port 758ms

Console output after:
Describing vCenter Configuration: NFC-UseSSL.Vester.ps1
Describing vCenter Configuration: SMTP-Port.Vester.ps1
 [+] vCenter 192.168.10.220 - SMTP Port 501ms

Same problem with the XML that is created, which I parse for XesterUI.

**Comment by jpsider** [comment]
I'm happy to submit a PR, but might want to wait until #114 is completed.

**Comment by brianbunke** [comment]
This will be fixed in #129, once merged.

We talked about this briefly in chat, and @jpsider pointed out that it's not working because `VesterTemplate.Tests.ps1` assumes an `$Object.Name` property on all inventory objects, but the vCenter server itself is just a string.

Personally, I would like to solve this by still referencing `$cfg.vcenter.vc`. Right now, it's possible for you to be connected to multiple vCenters, and then `Invoke-Vester` against a different server than the current `$global:DefaultVIServer`.

**Comment by brianbunke** [comment]
#129 has merged into `master`. 👍
