### ISSUE TITLE
Discuss Invoke-Vester

### ISSUE THREAD

**Issue by brianbunke** [WahlNetwork/Vester#29]
See PR #28.

This issue is to discuss pros/cons of:
1. Converting Vester to a PowerShell module
2. Introducing `Invoke-Vester`

Pros:
- No more hashtables to pass `-Remediate` and `-Config`
- Free to order tests (and rearrange) as desired
  - In reference to #12, where `Config.Tests.ps1` was running first because of #AlphabeticPrivilege
  - And can prompt user to define `Config.ps1` if `Invoke-Pester` is called against a default file
- Can call VMs/Hosts/whatever once up front, instead of within every test
- Support for `-WhatIf`
- Tags can auto-suggest/complete thanks to ValidateSet
- Better docs. Comment-based help on `Invoke-Pester`, `help about_Vester`, etc.

Cons:
- Have to manually duplicate each Pester parameter? I think
  - And would have to manually update when Pester adds new features
- ^ That's a really big con

Examples of use:

```
Invoke-Vester
Invoke-Vester -Remediate -WhatIf
# Note auto-complete when adding tags
Invoke-Vester -Tag cluster,host -ExcludeTag nfs
```

**Comment by equelin** [comment]
I like the idea! You'll have all my attention if you can suppress hashtable for `-Remediate` and `-Config`...

Another pro argument, Modules are a great for:

- Easily shipping codes to the user (Powershell Gallery)
- Versioning the code
- Adding private "helper" functions

**Comment by chriswahl** [comment]
Regarding having to keep our code updated along with Pester, I agree this is a concern. However, I think there's only 6-8 parameters we'd have to support and I've not seen any major changes in the param structure for Pester in the past. We could also query the version of Pester to determine what structure we use to pass params.

I think the good out weighs the bad in this case, especially since we can force the order of tests and clear up the nested hashtable complexity involved with the `Script` param.

**Comment by equelin** [comment]
Can I sugest using the informations of this [blog ](http://ramblingcookiemonster.github.io/Building-A-PowerShell-Module/) for building the module ? You'll find some best practices that are relevant for efficiently develop and maintain powershell module.

@chriswahl, If I'm not wrong you're using it for your Rubrik's powershell module?

**Comment by brianbunke** [comment]
I'm all for following those module best practices. I may or may not have rushed out that pull request so Chris could skim it before his session, haha.

I should say, this will require further refactoring of existing tests, and we'll probably be developing against this branch for a few weeks before merging. But I like its promise!

**Comment by chriswahl** [comment]
Agreed. And yes @equelin I use that same methodology for the Rubrik module. I would like to focus efforts on the creation of a polished Module and discussing complex tests in #38 before trying to onboard more tests. Otherwise I forsee us having to fix the new tests to match the proposed framework resulting in technical debt.

**Comment by cars** [comment]
If we do a module with  #38 in mind I wonder if it'd be worth having an option or cmdlet to list tags 
and/or tests?

**Comment by brianbunke** [comment]
I thought about this on the plane last night. Long story short, this module might need to abstract away _a lot_ of Pester. This is relevant to the tag discussion (#38) in the following example:

- User calls `Invoke-Vester`; let's assume that it's going to run every VM test
- For performance, we want `Invoke-Vester` to `Get-VM` only once, storing it in `$VMList` or whatever
- How do we know up front that a VM test is going to run, and that we should bother calling `Get-VM`?
  - The tags are buried in the Tests files, which we haven't checked yet
  - You can't `$VMList = Get-VM -Name $config.scope.vm` within the first test and have that variable cross over to other tests
    - Without doing some ugly `$global:VMList` nonsense

I don't have a perfect answer for this yet. I agree with everyone that tag sprawl is super lame.

If someone wants to run one test and not the others, @chriswahl and I talked about treating this solely as a corner case, and telling them to use the Describe name. Meaning:

- In the HA example, something like `Invoke-Vester -Tag ha -TestName '*state*'`
  - Grabs the HA test but only runs the state test (top level)
- In the DNS example, something like `Invoke-Vester -Tag dns -TestName '*server*'`
 - Tests for DNS servers, ignores DNS search domains

This is a long way of saying the following:

1. I probably need to devise a way to store tags in a different way than just the Pester-supported Describe block, as mentioned by @mattallford / @cars
2. I'm liking @cars's suggestion of having a separate cmdlet to list tags/tests
3. However, Invoke-Vester may just need a custom way of filtering tests, separate from Pester's TestName/Tag support

I'll continue to think about it and poke at the problem, updating here when I have some working code for review.

**Comment by cars** [comment]
@brianbunke  One issue I can see with the above is it might mean having to rewrite the some of the tests. The Disable-Limit, Disconnect-CDROM and Delete-Snapshots tests all call Get-VM inside either the Describe or It blocks.  If you did this for VMs then it seems you'd need to for consistency do the same for hosts and clusters?

**Comment by chriswahl** [comment]
I don't see how we can globally pull all of the required data, and then run tests, especially since some tests may be skipped by the user. To me, although it's more efficient to pull data once globally, it still makes more sense architecturally to pull data in the test. However, we can structure the tests so that they are themselves efficient (such as what was done in the NFS tests).

**Comment by brianbunke** [comment]
Calling interested parties into #41 for preliminary code review!

**Comment by chriswahl** [comment]
I'm going to close this thread as development has moved along quite nicely on `module` today. We can re-open if required.
