### ISSUE TITLE
#requires statements are missing VMware.VimAutomation.Core

### ISSUE THREAD

**Issue by cwiggins1** [WahlNetwork/Vester#54]
running powercli 5.1 on windows 10 x64 using a simple script; 
Add-PSSnapin VMware.VimAutomation.Core

write-host -ForegroundColor Green "Connecting to VirtualCenter Server"
Connect-VIServer -Server vcenter -Session $sessionId -ErrorVariable currentError

Invoke-Pester .\

 [-] Error occurred in test script 'C:\Users\u376504\Desktop\vblock capacity charts\Vester-master\Configs\Config.Tests.ps1' 37ms
   ScriptRequiresException: The script 'Config.Tests.ps1' cannot be run because the following modules that are specified by the "#requires" statements of the script are missing: VMware.VimAutomation.Core.
   at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Pester.psm1: line 297
   at Invoke-Pester, C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Pester.psm1: line 310
   at <ScriptBlock>, <No file>: line 6

seems to be no module version of VMware.VimAutomation.Core? can we just use the snapin

**Comment by brianbunke** [comment]
Hello!

We're primarily (exclusively?) testing with PowerCLI 6.3 R1. You're correct that the test scripts are looking for a module version of `VMware.VimAutomation.Core`, and 5.1 was still using snapins for everything.

The requires statement is primarily there because some of the cmdlets/parameters inside the tests may not exist in your version. (I haven't tested downlevel, and I'm guessing others also have not.)

Any specific reason you're using PowerCLI 5.1? My impression is that 6.3 R1 is fully backwards compatible, but it's entirely possible I'm missing something.

**Comment by chriswahl** [comment]
Correct @brianbunke - PowerCLI is backwards compatible and the PowerCLI team encourages everyone to run the latest version.

@cwiggins1 - You are welcome to manually load the snappin if desired. I'd suggest updating to the latest release of PowerCLI which will continue to phase out snappins in favor of modules.

**Comment by cwiggins1** [comment]
Upgraded to 6.3 r1 and all is well - thanks
