### ISSUE TITLE
Soliciting feedback

### ISSUE THREAD

**Issue by brianbunke** [WahlNetwork/Vester#91]
Hey there!

Vester is fairly stable right now, with a version 1.0.1 published on the PS Gallery! _(read: I'm done drastically screwing with things for the time being)_

Now seems like a pretty good time to ask everyone to try it out again, and to please speak up if you like or don't like certain things.

If you're not sure how to wrap your head around everything...

1. http://vester.readthedocs.io/en/latest/
2. `help about_Vester`
3. I believe @chriswahl will be posting a blog ~~soon~~
    * [vSphere Configuration Management with Vester](http://wp.me/p2Iwqe-3QQ)
4. I've got documentation to review/update and a couple blogs on the changes to bang out as well
    * [Part 1 - Introducing Vester](http://www.brianbunke.com/blog/2017/03/07/introducing-vester/)
    * [Part 2 - Tips & Tricks](http://www.brianbunke.com/blog/2017/03/08/vester-2-vest-harder/)
    * [Part 3 - Write (& Contribute!) Your Own Tests](http://www.brianbunke.com/blog/2017/03/09/write-your-own-vester-test/)

Keep an eye out for those if you're interested, but in the meantime, try this on for size:

```posh
# Assuming you've used the PowerShell Gallery. You could just DL the GitHub zip if preferred
Install-Module Vester
Import-Module Vester
# Module requirements "Pester" & "VMware.VimAutomation.Core" automatically load into the session

Connect-VIServer your.vcenter.com

# Do you care about Distributed Switches?
# PowerCLI doesn't do implicit module loading yet, so manually import any other needed modules
Import-Module VMware.VimAutomation.Vds

# This step requires you to be running PowerShell as admin
# Because default PS Gallery install location is inside C:\Program Files\
New-VesterConfig
# Config.json now exists in the module's \Config folder

# By default, run all included `.Vester.ps1` tests using the newly created config.json
Invoke-Vester
```

If you have general feedback, feel free to reply on this issue :arrow_down: , or let us know in the VMware Code #vester Slack channel. If you find a bug or have an enhancement request, please also feel free to just open a new issue.

Thanks! Hope you enjoy!

**Comment by jeffgreenca** [comment]
Running Invoke-Vester -Remediate -Whatif allows some changes to execute.  If $Fix code for a test uses cmdlets without -WhatIf support, real changes may be made.  For example, VIB-AcceptanceLevel.Vester.ps1 is susceptible to this problem due to its use of Get-EsxCli.

Rather than rely on each devs test to handle Should execution properly, I'm wondering if some wrapper logic would be appropriate before executing the $Fix block.  But I'm not sure how Pester handles that exactly so...

**Comment by boyler05** [comment]
Chris - thanks for getting this project started from the ground up!  I attended your VMworld session and started working with Vester from the very beginning.

Brian - thanks for all of the enhancements to Vester, and for the excellent blog posts.  VERY helpful!  I was trying to access the "http://vester.readthedocs.io/en/latest/" URL you provided, but even though it says "latest", it's actually the old documentation from November, before the JSON config file format was introduced.  It would probably be good to take down that link entirely, because it's pretty confusing for first-time Vester users.  Also it seems that this link is the primary link from the GitHub page.  I propose re-directing to your well-written blog pages instead, until the documentation can be updated.

Second, a question for you.  The late 2016 version of Vester included quite a few tests that I don't see in the v1.0.1 release.  Are they coming back?  The ones I liked were:

- vCenter Task Retention
- vCenter SMTP Server
- vCEnter Mail Server
- NetDump
- Delete Snapshots
- Syslog Firewall Exception
- VM Time Sync

Thanks again for all your work on this!  I'll be contributing some tests in the near future.

**Comment by brianbunke** [comment]
Thanks, @boyler05, and totally agreed. I was hoping I'd churn out the documentation last weekend, but had trouble getting up to speed with those files, and it's not done. I'll update the readme in the meantime.

I want all of those tests to come back. When I introduced the new test format, I ported the host tests, and one from each other scope, and left the rest. My hope was that others would help port, because I didn't want to be the only one who understood the new format, and to generate feedback on any potential problems with the new format. @haberstrohr hooked us up with the DRS cluster tests, but obviously those you listed (and others) are still standing outside, looking through the living room window of our new home.

I've also been specifically advertising Vester as solving a real-world problem I once had with stale snapshots, in blog posts and in the newly recorded online session, and it doesn't do that right now because we haven't ported the test. 😆 I think I'll open an issue about the test porting.

**Comment by haberstrohr** [comment]
I'll look into getting those tests ported this weekend. I've been using the project for my own benefit (security configuration tests, etc.) but am happy to give back.

**Comment by michaeltlombardi** [comment]
Hullo! I dropped in my specific thoughts via other issues, but overall I like this project. I had never considered remediating tests this way before, but it's pretty neat. 

I'm available to help with documentation efforts specifically but will try to help out with other stuff too. I'm pretty passionate about documentation and it's one of the best ways for you to drive adoption/contribution to this project.
